# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

env.aProgram('fcgi_main', ['main.c', 'fcgi_handler.c'], LIBS=['simple_static', 'lemon_static', 'pthread'])
env.aProgram('fcgi_server', ['server.c', 'fcgi_handler.c'], LIBS=['simple_static', 'lemon_static', 'pthread'])
