# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env.Append(CPPPATH=['#/include/'])

env.Append(LIBPATH=['#/lib/'])

env.aProgram('io_time_event_test', ['time_event_test.c'], LIBS=['simple_static', 'pthread'])
