# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env.Append(CPPPATH=['#/include/'])

env.Append(LIBPATH=['#/lib/'])

env.aProgram('client', ['client.c'], LIBS=['simple_static', 'pthread'])
env.aProgram('server', ['server.c'], LIBS=['simple_static', 'pthread'])
