# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

env.Append(CPPPATH=['#/include/'])
env.Append(LIBPATH=['#/lib/'])

env.aSubs('echo')
env.aSubs('http')
env.aSubs('fastcgi')
