# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

# simple
env.Append(CPPPATH=['#/include/'])
env.Append(LIBPATH=['#/lib/'])

# lemon
env.Append(CPPPATH=['#/deps/lemon/include/'])
env.Append(LIBPATH=['#/deps/lemon/lib/'])

env.aSubs('echo')
env.aSubs('http')
env.aSubs('fastcgi')
