# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

# simple-pool
env.Append(CPPPATH=['#/include/'])
env.Append(LIBPATH=['#/lib/'])

# simple
env.Append(CPPPATH=['#/deps/simple/include/'])
env.Append(LIBPATH=['#/deps/simple/lib/'])

env.aSubs('echo')
env.aSubs('echo-huge-data')
env.aSubs('fastcgi')
