# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env.Append(CPPPATH='#/include/simple/')
env.Append(CPPPATH='#/deps/lemon/include/')

obj = []
obj += Glob('*.c')

env.aStaticLibrary("simple_static", obj) 
env.aSharedLibrary("simple_shared", obj) 

env.aSubs('unittest')
