# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env.Append(CPPPATH=['#/include/'])

env.Append(LIBPATH=['#/lib/'])

env.aProgram('logging_test', ['logging_test.c'], LIBS=['simple_static', 'pthread'])
