# -*- mode: python -*-
# -*- coding: utf-8 -*-

Import('env')

env = env.Clone()

env.Append(LIBPATH=['#/lib/'])
env.Append(LIBPATH=['#/deps/simple/lib/'])

lib = [
    'simple_pool_static',
    'simple_static',
]

env.aProgram(
    "message_unittest", 
    ['message_unittest.c'], 
    LIBS=lib)
